### ISSUE TITLE
omg thanks

### ISSUE THREAD

**Issue by 360manxxx** [Spiderlover/Toontown-2.0#1]
thanks spiderlover! extracting the folder now <3

**Comment by Spiderlover** [comment]
you should wait, all of the files are not done committing :) It's currently working TTO source code, but I am planning to heavily modify it.

**Comment by 360manxxx** [comment]
how long?

**Comment by Spiderlover** [comment]
It's going to take a while, so by tomorrow

**Comment by 360manxxx** [comment]
ok see ya then
