### ISSUE TITLE
Toontown Offline

### ISSUE THREAD

**Issue by loganotoon** [Spiderlover/Toontown-2.0#15]
Hey,

As petty as this probably sounds, this is just a blatant 1:1 rip of an old build of Toontown Offline. I kindly ask that this repository be taken down as I have requested several times on several occasions that the old build of the game is not to be redistributed as a majority of the work is from the TTI and TTR teams respectively with only a minor number of bug fixes thrown in by myself and a few others. "Projects" like this are a core reason why the community is suffering and will likely die off quickly. Do your own work, and don't claim the work of others as your own.

Thanks.

**Comment by mgracer48** [comment]
understand @Spiderlover  lets try this again this time with TTR source

**Comment by mgracer48** [comment]
and if u get mad at us for copying TTR dont be because toontown offline used TTR source

**Comment by loganotoon** [comment]
The difference is the Offline team didn't claim the source as their own. They gave credit where it was due. Read the last line of my post again ("Projects" like this are a core reason why the community is suffering and will likely die off quickly. Do your own work, and don't claim the work of others as your own.") Simply cloning TTRs source and calling it your own will get you nowhere.

**Comment by mgracer48** [comment]
Look will give credit to the original source ok?

**Comment by Spiderlover** [comment]
@loganotoon Thanks for staying calm and not going all rage mode like what DenialMC and the Stride team did with Toontown Crystal and I did give credit for the code in the Thanks section on the Readme
